project:
  type: book
  output-dir: docs

book:
  title: "Environmental Data Literacy"
  author: "Rodney J. Dyer"
  date: "1/6/2026"
  repo-url: "https://github.com/dyerlab/EnvironmentalDataLiteracy/"
  chapters:
    - index.qmd
    - Introduction.qmd
    - part: R_Ecosystem.qmd
      chapters:
        - R.qmd
        - Positron.qmd
        - DataTypesContainers.qmd
        - Markdown.qmd
        - FactorData.qmd
        - Tidyverse.qmd
        - TabularData.qmd
        - Graphics.qmd
        - Functions.qmd
        - Publishing.qmd
    - part: SpatialData.qmd
      chapters:
      - Projections.qmd
      - PointData.qmd
      - LinesPolygons.qmd
      - RasterData.qmd
    - part: StatisticalInferences.qmd
      chapters:
      - FrequentistBayesianInferences.qmd
      - Contingency.qmd
      - Correlation.qmd
      - Regression.qmd
      - AnalysisOfVariance.qmd
      - Ordination.qmd  
  appendices: 
    - References.qmd
    - DataSets.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    toc-depth: 2 
    respect-user-color-scheme: true
    css: media/style.css
    theme:
      - cosmo
      - brand

execute:
  warning: false
  message: false
  error: false
  freeze: auto  # set to false for release 
  eache: true   # set to false for release


